name: CI

on:
  push:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure with CMake
      run: cmake -B build -S .
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Run tests
      working-directory: ./build
      run: ./bin/runAllTests
